version: '3.8'

services:
  app:
#    image: docker/demo:v1
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hibernatedb
      SPRING_DATASOURCE_USERNAME : admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db :
    image: mysql:8.0.32
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hibernatedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root